name: hunt
description: An example of playhunt lib use
dependencies:
  polymer: any
  core_elements: any
  paper_elements: any
  crypto: '>=0.9.0 <1.0.1'
transformers:
- polymer:
    entry_points:
    - web/hunts.html
    - web/createhunt.html
