name: playhunt
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Giovanni Laquidara <glaquidara@gmail.com>
#homepage: https://www.laquysoft.com
dependencies:
  crypto: '>=0.9.0 <1.0.1'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
  browser: '>=0.10.0+2 <0.11.0'